# Generated by Django 4.2.4 on 2023-08-07 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="telephone_number",
            field=models.CharField(max_length=255),
        ),
    ]
