# Generated by Django 4.2.4 on 2023-08-10 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("salon", "0002_alter_client_telephone_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="procedure",
            name="additional_info",
        ),
    ]
